### ISSUE TITLE
Kernel trying to build and failing?

### ISSUE THREAD

**Issue by ClashTheBunny** [aosp-rockchip/manifests#1]
I just tried this:

```
source build/envsetup.sh; lunch aosp_pinenote-userdebug && ./build.sh -UCAu
```

and got this when I got to the kernel section:

```
Start build kernel

#### build completed successfully (10 seconds) ####

  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  YACC    scripts/kconfig/zconf.tab.c
  LEX     scripts/kconfig/zconf.lex.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/Makefile:109: *** No configuration exists for this target on this architecture.  Stop.
make: *** [Makefile:578: rk356x_eink.config] Error 2

#### failed to build some targets (2 seconds) ####

Build kernel failed!
```

I installed the normal debian/ubuntu packages:

```
sudo apt-get install git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig
```

 as well as:

```
repo
device-tree-compiler
python-is-python3
python3-pyelftools
bc
```

on a fully up to date debian 11.

**Comment by frap129** [comment]
Sorry I missed this! Your issue should be fixed now, the symlinks in the manifest weren't pointing at the right configs

**Comment by ClashTheBunny** [comment]
Still failing after a `repo sync`

```
Start build kernel

#### build completed successfully (10 seconds) ####

  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  YACC    scripts/kconfig/zconf.tab.c
  LEX     scripts/kconfig/zconf.lex.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
The base file '.config' does not exist.  Exit.
make[1]: *** [scripts/kconfig/Makefile:110: rk356x_eink.config] Error 1
make: *** [Makefile:578: rk356x_eink.config] Error 2

#### failed to build some targets (2 seconds) ####

Build kernel failed!
```

Do I need to blow it away or make clean or something?

**Comment by ClashTheBunny** [comment]
Here's the full build log after a repo sync:
https://gist.github.com/442cb6542b7a21ff4cf476295b2a82aa

**Comment by ClashTheBunny** [comment]
This started the kernel building, not sure if I'm going to get anything, but...
```
sudo apt install libssl-dev lz4 cpio rsync
cd kernel
curl https://gitlab.com/pgwipeout/quartz64_ci/-/raw/main/quartz64_defconfig?inline=false -o arch/arm64/configs/pinenote_defconfig
ARCH=arm64 make pinenote_defconfig
```

**Comment by ClashTheBunny** [comment]
Actually, I think I want to use the defconfig for this kernel version like so:
```
cd kernel
ARCH=arm64 make rk356x_eink_defconfig
```
and then running build.sh again.

**Comment by ClashTheBunny** [comment]
More missing packages:

```
sudo apt install lz4
```

**Comment by ClashTheBunny** [comment]
and add to it this... `cpio`

**Comment by ClashTheBunny** [comment]
🥳 `#### build completed successfully (03:05:31 (hh:mm:ss)) ####` 🎉
